### ISSUE TITLE
🚀 Feature: Redirect Join us button to given link

### ISSUE THREAD

**Issue by sudhanshutech** [GDSCITM/GDSCITM-official-website#107] opened 2023-04-03 05:17 UTC
### 📜 Feature Description

Redirect **join us** button in header to the given link -> https://gdsc.community.dev/institute-of-technology-and-management-gwalior/

![image](https://user-images.githubusercontent.com/90546692/229417574-462f854a-82b0-4211-8023-66387cabfb03.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Yes, I have read Code of Conduct.

**Comment by Sunny-25** [comment] 2023-04-03 05:40
I will complete this please assign this issue to me.

**Comment by HemanthPaila** [comment] 2023-04-05 08:36
Hey @sudhanshutech can I work on it? Could you please assign it to me? I am pretty free now and the issue is straightforward.

**Comment by sudhanshutech** [comment] 2023-04-05 11:44
Ok great to know @HemanthPaila

**Comment by HemanthPaila** [comment] 2023-04-05 13:02
Hey, @sudhanshutech I made a PR #136. Could you please review and merge it?
- if further changes are needed let me know.

**Closed** 2023-04-06 09:27 UTC
Labels: good first issue
